spring.datasource.url: jdbc:postgres://localhost:8081/tasklib
spring.datasource.username: test_user
spring.datasource.password: test_user
spring.jpa.hibernate.ddl-auto: create
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration