spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:8081/tasklib
    username: test_user
    password: test_user
    jpa.hibernate.ddl-auto: none